from app import app
from app.views import *
app.add_url_rule('/',view_func=HomeView.as_view('home2'))
app.add_url_rule('/',view_func=HomeView.as_view('home1'))
app.add_url_rule('/<int:page>',view_func=HomeView.as_view('home'))
app.add_url_rule('/reg',view_func=RegView.as_view('reg'))
app.add_url_rule('/login',view_func=LoginView.as_view('login'))
app.add_url_rule('/logout',view_func=LogoutView.as_view('logout'))
app.add_url_rule('/serch',view_func=SerchView.as_view('serch'))
app.add_url_rule('/new_post',view_func=NewView.as_view('new_post'))
app.add_url_rule('/center_person',view_func=PersonView.as_view('center_person'))
app.add_url_rule('/editperson',view_func=EditpersonView.as_view('editperson'))
app.add_url_rule('/post/<post_id>',view_func=PostViews.as_view('post'))
app.add_url_rule('/user/uername',view_func=Userviews.as_view('user'))
app.add_url_rule('/re_comment/<int:post_id>&<int:comment_id>&<string:user_id>',view_func=RecommentView.as_view('re_comment'))
app.add_url_rule('/editperson',view_func=EditpostView.as_view('edit'))
app.add_url_rule('/tag/<string:tag>&<int:page>',view_func=TagViews.as_view('tag'))
app.add_url_rule('/person/<string:fenlei1>',view_func=PersonFenleiView.as_view('peir'))
app.add_url_rule('/fenlei/<string:fenlei_name>&<int:page>',view_func=FenleiHome.as_view('fenlei'))