"""empty message

Revision ID: fdb5dc72e66b
Revises: 
Create Date: 2017-07-05 16:48:17.092075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb5dc72e66b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_token', sa.String(length=580), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_token')
    # ### end Alembic commands ###
